//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementForm
    {
        public int Id { get; set; }
        public string Form { get; set; }
        public int AchievementId { get; set; }
    
        public virtual Achievement Achievement { get; set; }
    }
}
