//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phrase
    {
        public int Id { get; set; }
        public string OriginalMessage { get; set; }
        public string CorrectedMessage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool WasRecognized { get; set; }
        public Nullable<int> MeasureUnitFId { get; set; }
        public Nullable<int> ActionFId { get; set; }
        public Nullable<int> AdditionalTextFId { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual Action Action { get; set; }
        public virtual AdditionalText AdditionalText { get; set; }
    }
}
