//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phrase
    {
        public int PhraseId { get; set; }
        public string OriginalMessage { get; set; }
        public string CorrectedMessage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool WasRecognized { get; set; }
        public Nullable<int> MeasureUnitFId { get; set; }
        public Nullable<int> ActionFId { get; set; }
        public Nullable<int> AdditionalTextFId { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual Action Action { get; set; }
        public virtual AdditionalText AdditionalText { get; set; }
    }
}
