//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievement
    {
        public int Id { get; set; }
        public string DateTime { get; set; }
        public int PhraseId { get; set; }
        public int FullAchievementId { get; set; }
        public Nullable<int> ShortAchievementId { get; set; }
        public int UserId { get; set; }
    
        public virtual Phrase Phrase { get; set; }
        public virtual FullAchievement FullAchievement { get; set; }
        public virtual ShortAchievement ShortAchievement { get; set; }
        public virtual User User { get; set; }
    }
}
